# Generated by Django 4.0.4 on 2022-04-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='last_version',
        ),
    ]
