# Generated by Django 4.0.4 on 2022-05-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0002_app_appfile_app_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='image',
            new_name='appImage',
        ),
    ]
